create extension if not exists pgcrypto;

create type public.advertisement_status as enum (
  'Draft',
  'Pending',
  'Published',
  'Archived'
);

create table public.roles (
  id smallint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  constraint roles_name_chk check (char_length(name) >= 2)
);

create table public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id smallint not null references public.roles(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint categories_name_chk check (char_length(trim(name)) > 0),
  constraint categories_slug_chk check (char_length(trim(slug)) > 0)
);

create table public.advertisements (
  id bigint generated by default as identity primary key,
  uuid uuid not null unique default gen_random_uuid(),
  title text not null,
  description text not null,
  price numeric(12, 2) not null,
  category_id bigint not null references public.categories(id),
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_phone text,
  status public.advertisement_status not null default 'Draft',
  primary_image_uuid uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  archived_at timestamptz,
  constraint advertisements_title_chk check (char_length(trim(title)) > 0),
  constraint advertisements_description_chk check (char_length(trim(description)) > 0),
  constraint advertisements_price_chk check (price >= 0)
);

create table public.advertisement_images (
  id bigint generated by default as identity unique,
  uuid uuid primary key default gen_random_uuid(),
  advertisement_uuid uuid not null references public.advertisements(uuid) on delete cascade,
  position integer not null,
  file_path text not null,
  created_at timestamptz not null default now(),
  constraint advertisement_images_position_chk check (position >= 0),
  constraint advertisement_images_file_path_chk check (char_length(trim(file_path)) > 0),
  constraint advertisement_images_position_unique unique (advertisement_uuid, position)
);

alter table public.advertisements
  add constraint advertisements_primary_image_uuid_fk
  foreign key (primary_image_uuid)
  references public.advertisement_images(uuid)
  on delete set null;

create table public.advertisement_archive (
  advertisement_uuid uuid primary key,
  title text not null,
  description text not null,
  owner_id uuid not null references auth.users(id) on delete restrict,
  archived_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_advertisements_updated_at
before update on public.advertisements
for each row
execute function public.set_updated_at();

create or replace function public.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = check_user_id
      and r.name = 'admin'
  );
$$;

insert into public.roles (name)
values ('admin'), ('user')
on conflict (name) do nothing;

alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.categories enable row level security;
alter table public.advertisements enable row level security;
alter table public.advertisement_images enable row level security;
alter table public.advertisement_archive enable row level security;

create policy roles_select_admin_only
on public.roles
for select
to authenticated
using (public.is_admin(auth.uid()));

create policy user_roles_select_own_or_admin
on public.user_roles
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

create policy user_roles_admin_manage
on public.user_roles
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy categories_public_read
on public.categories
for select
to anon, authenticated
using (is_active = true);

create policy categories_admin_manage
on public.categories
for all
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy advertisements_select_policy
on public.advertisements
for select
to anon, authenticated
using (
  status = 'Published'
  or owner_id = auth.uid()
  or public.is_admin(auth.uid())
);

create policy advertisements_insert_owner_or_admin
on public.advertisements
for insert
to authenticated
with check (owner_id = auth.uid() or public.is_admin(auth.uid()));

create policy advertisements_update_owner_or_admin
on public.advertisements
for update
to authenticated
using (owner_id = auth.uid() or public.is_admin(auth.uid()))
with check (owner_id = auth.uid() or public.is_admin(auth.uid()));

create policy advertisements_delete_owner_or_admin
on public.advertisements
for delete
to authenticated
using (owner_id = auth.uid() or public.is_admin(auth.uid()));

create policy advertisement_images_select_policy
on public.advertisement_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.advertisements a
    where a.uuid = advertisement_images.advertisement_uuid
      and (
        a.status = 'Published'
        or a.owner_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

create policy advertisement_images_insert_owner_or_admin
on public.advertisement_images
for insert
to authenticated
with check (
  exists (
    select 1
    from public.advertisements a
    where a.uuid = advertisement_images.advertisement_uuid
      and (a.owner_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

create policy advertisement_images_update_owner_or_admin
on public.advertisement_images
for update
to authenticated
using (
  exists (
    select 1
    from public.advertisements a
    where a.uuid = advertisement_images.advertisement_uuid
      and (a.owner_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.advertisements a
    where a.uuid = advertisement_images.advertisement_uuid
      and (a.owner_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

create policy advertisement_images_delete_owner_or_admin
on public.advertisement_images
for delete
to authenticated
using (
  exists (
    select 1
    from public.advertisements a
    where a.uuid = advertisement_images.advertisement_uuid
      and (a.owner_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

create policy advertisement_archive_admin_select
on public.advertisement_archive
for select
to authenticated
using (public.is_admin(auth.uid()));

create policy advertisement_archive_admin_insert
on public.advertisement_archive
for insert
to authenticated
with check (public.is_admin(auth.uid()));

create policy advertisement_archive_admin_update
on public.advertisement_archive
for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

create policy advertisement_archive_admin_delete
on public.advertisement_archive
for delete
to authenticated
using (public.is_admin(auth.uid()));
